finished second level "B" spells
magicalmusings/magicalmusings.github.io pull request #43
Opened 2020-10-14 14:00 UTC by ChrisSpangler

finished the second level "b" spells

2020-10-14 15:47 UTC, magicalmusings commented on _posts/spells/cantrips/2020-10-13-spells-2-augury.md
> +school: Divination
Divination (ritual)

2020-10-14 15:47 UTC, magicalmusings commented on _posts/spells/cantrips/2020-10-13-spells-2-augury.md
> +source: "Xanathar's Guide to Everything (XGtE)"
Players Handbook or PHB

2020-10-14 15:49 UTC, magicalmusings commented on _posts/spells/cantrips/2020-10-14-spells-2-beast-sense.md
> +school: Divination
Divination (ritual)

2020-10-14 15:54 UTC, magicalmusings requested changes
These are great! just a couple minor edits I mentioned in comments, and a couple of points here:

- All of these spells are actually from the Players Handbook ,or PHB. On the https://5e.tools/spells.html#branding%20smite_phb you can see the source on there in either the table or the spell card itself. 
- All of these spells are currently in the _posts/spells/cantrips/ folder, just move them to _post/spells/second-level/ folder 

Other than that, ready to approve and merge when those changes are made! Thanks @ChrisSpangler , let me know if you got any questions or concerns.

2020-10-14 23:35 UTC, ChrisSpangler commented
Added the corrections - wasn't sure if you wanted "Players Handbook" or "PHB" or "Players Handbook or PHB" (together)

Let me know and I will make the fixes!

2020-10-14 23:47 UTC, magicalmusings commented
Probably just 'Player's Handbook (PHB)' or 'Player's Handbook' is fine @ChrisSpangler

2020-10-15 00:19 UTC, magicalmusings requested changes
Like I said via comment, just change to either 'Player's Handbook (PHB)' or 'Player's Handbook' and we'll be good to merge!

2020-10-15 00:34 UTC, ChrisSpangler commented
Changes made :) - thank you for your patience

2020-10-15 00:36 UTC, magicalmusings approved these changes

2020-10-15 00:39 UTC, merged

2020-10-15 00:39 UTC, magicalmusings commented
No worries! I am pretty new to Github as well, I only know how to handle these PRs because of my Open Source Software class in college. Apologies on any weird notifications, was setting up some Continuous Integration to automatically check whether things are not going to break the site before I merge pull requests / commits. 

Thanks for your help @ChrisSpangler!